0.5.5cnc1-alt3
- Introduced APT::Ignore-dpkg support and set this flag by default,
  to address #0002119.

diff --git a/apt/dselect/install b/apt/dselect/install
--- a/apt/dselect/install
+++ b/apt/dselect/install
@@ -1,15 +1,22 @@
-#!/bin/sh
+#!/bin/bash
+
+# Set the textdomain for the translations using $"..."
+TEXTDOMAIN="apt"
 
 # Get the configuration from /etc/apt/apt.conf
 CLEAN="prompt"
 OPTS="-f"
 APTGET="/usr/bin/apt-get"
 DPKG="/usr/bin/dpkg"
+DPKG_OPTS="--admindir=$1"
+APT_OPT0="-oDir::State::status=$1/status"
+APT_OPT1="-oDPkg::Options::=$DPKG_OPTS"
 set -e
 RES=`apt-config shell CLEAN DSelect::Clean OPTS DSelect::Options \
-                      DPKG Dir::Bin::dpkg APTGET Dir::Bin::apt-get \
-		      ARCHIVES Dir::Cache::Archives/ \
-		      WAIT DSelect::WaitAfterDownload`
+                      DPKG Dir::Bin::dpkg/f APTGET Dir::Bin::apt-get/f \
+		      ARCHIVES Dir::Cache::Archives/d \
+		      WAIT DSelect::WaitAfterDownload/b \
+		      CHECKDIR DSelect::CheckDir/b`
 eval $RES
 set +e
 
@@ -22,7 +29,7 @@ yesno() {
 		case $2 in
 			Y|y)	defp="[Y/n]" def=y;;
 			N|n)	defp="[y/N]" def=n;;
-			*)	echo "Bad default setting!" 1>&2; exit 1;;
+			*)	echo $"Bad default setting!" 1>&2; exit 1;;
 		esac
 	else
 		defp="[y/N]" def=n
@@ -39,14 +46,13 @@ yesno() {
 	echo $ans | tr YN yn
 }
 
-OLDLS=`ls -ld $ARCHIVES`
-if [ x$WAIT = "xyes" ]; then
-   $APTGET $OPTS -d dselect-upgrade
-   echo "Press enter to continue." && read RES
-   $APTGET $OPTS dselect-upgrade
+if [ x$WAIT = "xtrue" ]; then
+   $APTGET $OPTS "$APT_OPT0" "$APT_OPT1" -d dselect-upgrade
+   echo $"Press enter to continue." && read RES
+   $APTGET $OPTS "$APT_OPT0" "$APT_OPT1" dselect-upgrade
    RES=$?
 else
-   $APTGET $OPTS dselect-upgrade
+   $APTGET $OPTS "$APT_OPT0" "$APT_OPT1" dselect-upgrade
    RES=$?
 fi
 
@@ -64,34 +70,39 @@ if [ $RES -eq 0 ]; then
    fi
 
    NEWLS=`ls -ld $ARCHIVES`
-   if [ "x$OLDLS" = "x$NEWLS" ]; then
-      exit 0
+   if [ x$CHECKDIR = "xtrue" ]; then
+      if [ "x$OLDLS" = "x$NEWLS" ]; then
+         exit 0
+      fi
    fi
    
    # Check the cleaning mode
    case `echo $CLEAN | tr '[:upper:]' '[:lower:]'` in
      auto)
-       $APTGET autoclean && echo "Press enter to continue." && read RES && exit 0;
+       $APTGET "$APT_OPT0" "$APT_OPT1" autoclean &&
+	   echo $"Press enter to continue." && read RES && exit 0;
        ;;
      always)
-       $APTGET clean && echo "Press enter to continue." && read RES && exit 0;
+       $APTGET "$APT_OPT0" "$APT_OPT1" clean &&
+	   echo $"Press enter to continue." && read RES && exit 0;
        ;;
      prompt)
        exec 3>&1
-       if [ `yesno "Do you want to erase the downloaded .deb files?" y` = y ]; then
-          $APTGET clean && echo "Press enter to continue." && read RES && exit 0;
+       if [ `yesno $"Do you want to erase any previously downloaded .deb files?" y` = y ]; then
+          $APTGET "$APT_OPT0" "$APT_OPT1" clean &&
+	    echo $"Press enter to continue." && read RES && exit 0;
        fi
        ;;
      *) 
        ;;
    esac   
 else
-   echo "Some errors occurred while unpacking. I'm going to configure the"
-   echo "packages that were installed. This may result in duplicate errors"
-   echo "or errors caused by missing dependencies. This is OK, only the errors"
-   echo "above this message are important. Please fix them and run [I]nstall again"
-   echo "Press enter to continue."
-   read RES && $DPKG --configure -a
+   echo $"Some errors occurred while unpacking. I'm going to configure the"
+   echo $"packages that were installed. This may result in duplicate errors"
+   echo $"or errors caused by missing dependencies. This is OK, only the errors"
+   echo $"above this message are important. Please fix them and run [I]nstall again"
+   echo $"Press enter to continue."
+   read RES && $DPKG "$DPKG_OPTS" --configure -a
    exit 100
 fi
 
diff --git a/apt/tools/genbasedir b/apt/tools/genbasedir
--- a/apt/tools/genbasedir
+++ b/apt/tools/genbasedir
@@ -1,93 +1,59 @@
 #!/bin/sh
 #
-# $Id: genbasedir,v 1.21 2001/12/12 14:50:43 kojima Exp $
+# $Id: genbasedir,v 1.6 2002/09/04 22:48:37 niemeyer Exp $
 #
 # This script generates the contents of the base/ directory, by creating
 # the pkglists and the hash file. Update the components directory to contain
 # the components of your repository.
 #
-# $Log: genbasedir,v $
-# Revision 1.21  2001/12/12 14:50:43  kojima
-# fixed genbasedir for --flat and relative --topdir specifications
-# fixed --flat in gensrclist
-#
-# Revision 1.20  2001/11/30 20:40:27  kojima
-# patched --progress stuff from stelian
-#
-# Revision 1.19  2001/11/09 21:13:25  kojima
-#         * Skips correctly over empty package directories
-#
-#         * Adds the --bz2only argument which makes genbasedir
-#         to generate only the .bz2 compressed versions of pkglist
-#         and srclist (space gain...)
-#
-#         * Doesn't change the timestamps on pkglists/srclists if
-#         the contents are not modified (making possible for example
-#         to make several consecutive runs of genbasedir without
-#         having the apt clients download the indexes again and again).
-#
-#         * Some minor cleanups (remove the temporary files in /tmp
-#         at the end of the script etc).
-#
-# Revision 1.18  2001/03/11 14:36:28  claudio
-# Added appropriate message at the end of script.
-#
-# Revision 1.17  2001/01/04 21:26:14  kojima
-# fixed some mem leaks
-#
-# Revision 1.16  2000/12/10 13:42:58  claudio
-# Added linefeeds to usage message, replaced spaces for tabs
-#
-# Revision 1.15  2000/11/08 21:30:00  kojima
-# fixed bug in release retrieval code
-#
-# Revision 1.14  2000/11/08 20:40:23  kojima
-# fixed compat prob with bash1
-#
-# Revision 1.13  2000/11/06 12:53:49  kojima
-# fixed compile errors for RedHat 6.x (with gcc -Wall -Werror)
-#
-# Revision 1.12  2000/10/31 20:30:42  kojima
-# some updates
-#
-# Revision 1.11  2000/10/30 16:41:18  kojima
-# fixed genbasedir
-#
-# Revision 1.9  2000/10/29 21:49:54  kojima
-# fixed gensrclist/pkglist bug
-#
-# Revision 1.8  2000/10/25 17:17:35  kojima
-# *** empty log message ***
-#
-# Revision 1.7  2000/10/25 15:48:35  kojima
-# *** empty log message ***
-#
-# Revision 1.6  2000/10/23 14:31:57  kojima
-# *** empty log message ***
-#
-# Revision 1.5  2000/10/19 19:32:34  claudio
-# Language setting to generate a consistent pkglist.
-#
  
 usage="\
-Usage: genbasedir [<options>] <distribution> <comp1> [<comp2> ... <compN>]\n\
+Usage: genbasedir [<options>] <topdir> [<comp1> [<comp2> ...]]\n\
+
 Options:\n\
-   -s, --sign		Generate and sign hashfile\n\
-   --hashonly		Do hashfile stuff only\n\
-   --listonly		Generate pkglists/srclists and quit\n\
-   --bz2only		Generate only compressed lists\n\
-   --topdir=dir		Top directory of repository\n\
-   --progress		Show progress bars for genpkglist/gensrclist\n\
-   --updateinfo=file	Update information file\n"
+   -s, --sign         Generate and sign hashfile\n\
+   --default-key=ID   Use ID as gnupg secret key\n\
+   --hashonly         Do hash stuff only\n\
+   --listonly         Generate pkglists/srclists and quit\n\
+   --partial          Update just some of the already existent components\n\
+   --oldhashfile      Enable generation of old hashfile\n\
+   --bz2only          Generate only compressed lists\n\
+   --progress         Show progress bars for genpkglist/gensrclist\n\
+   --updateinfo=FILE  Update information file\n\
+   --flat             Use flat repository, where SRPMS and RPMS are in\n\
+                      the topdir (SRPMS are usually in 'topdir/..')\n\
+\n\
+Examples:\n\
+\n\
+   genbasedir /home/ftp/pub/conectiva\n\
+   genbasedir /home/ftp/pub/conectiva main extra devel\n\
+"
+
+getsize()
+{
+    tmp=`wc -c $1`
+    echo $tmp|cut -f1 -d\  
+}
+
+phashstuff()
+{
+    size=`getsize $1`
+    md5=`md5sum $1|cut -f1 -d\  `
+    echo " $md5 $size $2"
+}
 
 basedir=.
 signature=0
 listonly=0
 hashonly=0
-updateinfo=""
+partial=0
+oldhashfile=0
 mapi=0
 bz2only=0
+updateinfo=
 progress=
+flat=
+defaultkey=
 
 # bloat is necessary for non-Conectiva distros, at least RH,
 # because they use file dependencies with a non-predictable
@@ -95,17 +61,12 @@ progress=
 # never appear in dependencies.
 bloat=""
 
-
-# flat is for repositories where RPMS and SRPMS are kept in the
-# same directory level.
-flat=""
-
 while test $# -gt 0 ; do
-    case "${1}" in
+    case "$1" in
     -h | --help)
-        echo -e "${usage}"
+        echo -e "$usage"
         exit 0
-        ;;
+    ;;
     --mapi)
     	# hee hee hee..
         mapi=1
@@ -116,96 +77,115 @@ while test $# -gt 0 ; do
     --hashonly)
         hashonly=1
 	;;
+	--partial)
+		partial=1
+	;;
+    --oldhashfile)
+        oldhashfile=1
+	;;
     --bz2only)
         bz2only=1
-        ;;
+    ;;
     --updateinfo=*)
-	updateinfo=${1}
+		updateinfo=$1
 	;;
     --bloat)
-	bloat="--bloat"
-	;;
-    --flat)
-        flat="--flat"
+		bloat="--bloat"
 	;;
     --topdir=*)
-        topdir="`echo \"${1}\" | sed -e 's/^[^=]*=//'`"
-	if [ ! -d $topdir ]; then
-	     echo "Invalid top directory for distribution ${topdir}" 1>&2
-	     exit 1
-	fi
-        ;;
+		# Legacy
+		_topdir=$1
+    ;;
     --progress)
         progress="--progress"
-        ;;
+    ;;
+    --flat)
+        flat="--flat"
+    ;;
     -s | --sign)
-	signature=1;
+		signature=1
+	;;
+	--default-key=*)
+		defaultkey="\"$1\""
 	;;
     -*)
-        echo -e "${usage}" 1>&2
+        echo -e "$usage" 1>&2
         exit 1
-        ;;
+    ;;
     *)
         break
-        ;;
+    ;;
     esac
     shift
 done
 
-distro=${1}
+if [ -z "$*" ]; then
+	echo -e "$usage" 1>&2
+	exit 1
+fi
+
+topdir=`echo $topdir_/$1|tr -s /`
 shift
 
 components=$*
 
-if [ -z "$components" ]; then
-    echo -e "${usage}"
-    exit 0
+basedir_=base
+basedir=`echo $topdir/$basedir_|tr -s /`
+
+pkglist_=$basedir_/pkglist
+srclist_=$basedir_/srclist
+release_=$basedir_/release
+pkglist=$basedir/pkglist
+srclist=$basedir/srclist
+release=$basedir/release
+
+if [ ! -d "$topdir" ]; then
+	echo "error: invalid topdir: $topdir" 1>&2
+	exit 1
 fi
 
+if [ ! -d "$basedir" ]; then
+	echo -n "Creating base directory... "
+	mkdir $basedir
+	echo "done"
+fi
 
-getsize() {
-    tmp=`wc -c $1`
-    echo $tmp|cut -f1 -d\  
-}
+if [ -z "$components" ]; then
+	comps=$basedir/.components.tmp
+	rm -f $comps; touch $comps
+	for dir in $topdir/RPMS.* $topdir/SRPMS.* $topdir/../SRPMS.*; do
+		if [ -d $dir ]; then
+			echo $dir | sed 's/.*\.//' >> $comps
+		fi
+	done
+	components=`cat $comps|sort|uniq`
+	components=`echo $components` # eat newlines
+	rm -f $comps
+fi
 
-
-phashstuff() {
-    size=`getsize ${1}`
-    md5=`md5sum ${1}|cut -f1 -d\  `
-
-    echo " $md5 $size ${2}"
-}
-
-
-
-cd ${topdir}
-
-# this will fix the path if it was relative
-topdir=`pwd`
-
-basedir_=`echo ${distro}/base|tr -s /`
-basedir=${topdir}/$basedir_
-
-
-# release file
-# ------------
-
-#for comp in ${components}; do
-#     true > ${basedir}/release.$comp
-#           
-#done
-
+if [ -z "$components" ]; then
+	echo "error: no components found" 2>&1
+    exit 1
+else
+	echo "Components: $components"
+fi
 
 if [ $hashonly -ne 1 ]; then
+
 # package lists
 # -------------
 
-true > /tmp/srcidx.$$
+rm -f /tmp/srcidx.$$
+touch /tmp/srcidx.$$
 
-for comp in ${components}; do
-    echo -n "${comp}: "
+echo -n "Processing pkglists..."
 
-    echo -n "pkglist "
+for comp in $components; do
+	if [ ! -d $topdir/RPMS.$comp ]; then
+		continue
+	fi
+
+	echo -n " $comp"
 
     # Save older pkglist
     if [ -f $basedir/pkglist.$comp ]; then
@@ -213,14 +193,9 @@ for comp in ${components}; do
     fi
 
     if test x$updateinfo = x; then
-    	(cd $basedir; genpkglist $progress $bloat --index /tmp/srcidx.$comp.$$ $topdir/${distro} $comp)
+    	(cd $basedir; genpkglist $progress $bloat --index /tmp/srcidx.$comp.$$ $topdir $comp)
     else
-    	(cd $basedir; genpkglist $progress $bloat --index /tmp/srcidx.$comp.$$ --info $updateinfo $topdir/${distro} $comp)
-    fi
-    if [ $? -ne 0 ]; then
-	echo
-	echo "Error executing genpkglist."
-	exit 1
+    	(cd $basedir; genpkglist $progress $bloat --index /tmp/srcidx.$comp.$$ --info $updateinfo $topdir $comp)
     fi
 
     if [ -f $basedir/pkglist.$comp ]; then
@@ -246,47 +221,40 @@ for comp in ${components}; do
             fi
         fi
 
-        if [ $bz2only -eq 1 ]; then
-		rm -f $basedir/pkglist.$comp
-        fi
-
         rm -f $basedir/pkglist.$comp.old
         rm -f $basedir/pkglist.$comp.bz2.old
     fi
 
     cat /tmp/srcidx.$comp.$$ >> /tmp/srcidx.$$
 
-    echo "done"
 done
+echo " done"
 
-for comp in ${components}; do
-    echo -n "${comp}: "
+echo -n "Processing srclists..."
 
-    echo -n "srclist "
+for comp in $components; do
+	if [ -z "$flat" ]; then
+		srctopdir=`cd $topdir/..; pwd`
+	else
+		srctopdir=`cd $topdir; pwd`
+	fi
+
+	if [ ! -d $srctopdir/SRPMS.$comp ]; then
+		continue
+	fi
+
+	echo -n " $comp"
 
     # Save older srclist
     if [ -f $basedir/srclist.$comp ]; then
         mv -f $basedir/srclist.$comp $basedir/srclist.$comp.old
     fi
 
-
-    sfix="/.."
-    if test x$flat != x; then
-	sfix=""
-    fi
-
     if [ $mapi -ne 0 ]; then
-        (cd $basedir; gensrclist $progress $flat --mapi $topdir/${distro}${sfix} $comp /tmp/srcidx.$comp.$$)
+        (cd $basedir; gensrclist $progress $flat --mapi $srctopdir $comp /tmp/srcidx.$comp.$$)
     else
-        (cd $basedir; gensrclist $progress $flat $topdir/${distro}${sfix} $comp /tmp/srcidx.$$)
+        (cd $basedir; gensrclist $progress $flat $srctopdir $comp /tmp/srcidx.$$)
     fi
-    if [ $? -ne 0 ]; then
-	echo
-	echo "Error executing gensrclist."
-	exit 1
-    fi
-
-
 
     if [ -f $basedir/srclist.$comp ]; then
 
@@ -311,100 +279,219 @@ for comp in ${components}; do
             fi
         fi
 
-        if [ $bz2only -eq 1 ]; then
-		rm -f $basedir/srclist.$comp
-        fi
-
         rm -f $basedir/srclist.$comp.old
         rm -f $basedir/srclist.$comp.bz2.old
     fi
 
     rm -f /tmp/srcidx.$comp.$$
-
-    echo "done"
 done
+echo " done"
 
 fi
 
 rm -f /tmp/srcidx.$$
 
-if [ $listonly -eq 0 ]; then
-    # Save older hashfile
-    if [ -f $basedir/hashfile ]; then
-        mv -f $basedir/hashfile $basedir/hashfile.old
-    fi
-    hf=${basedir}/hashfile
-    true > $hf
+if [ $listonly -ne 0 ]; then
+	if [ $bz2only -eq 1 -a -f $pkglist.$comp ]; then
+		rm -f $pkglist.$comp
+	fi
+	if [ $bz2only -eq 1 -a -f $srclist.$comp ]; then
+		rm -f $srclist.$comp
+	fi
 else
-    hf=/dev/null
+	# component release file
+	# ----------------------
+
+	echo -n "Creating component releases..."
+	for comp in $components; do
+		if [ ! -f $release.$comp ]; then
+			echo -n " $comp"
+			echo "Archive: Unknown"      >> $release.$comp
+			echo "Component: $comp"      >> $release.$comp
+			echo "Version: Unknown"      >> $release.$comp
+			echo "Origin: Unknown"       >> $release.$comp
+			echo "Label: Unknown"        >> $release.$comp
+			echo "Architecture: unknown" >> $release.$comp
+			echo "NotAutomatic: false"   >> $release.$comp
+		fi
+	done
+	echo " done"
+
+	# release file
+	# ------------
+
+	if [ -f $release ]; then
+		mv -f $release $release.old
+		if [ $partial -eq 0 ]; then
+			echo -n "Updating global release file... "
+			sed -n -e "/^MD5Sum:/q" \
+				   -e "s/^Date:.*\$/Date: `date -R`/" \
+				   -e "s/^Components:.*\$/Components: $components/" \
+				   -e "p" $release.old > $release
+			echo "MD5Sum:" >> $release
+		else
+			echo -n "Partially updating global release file... "
+			sed -n -e "/^\$/q" \
+				   -e "s/^Date:.*\$/Date: `date -R`/" \
+				   -e "p" $release.old > $release.pre
+			for comp in $components; do
+				sed -e "\#^ .* $pkglist_.$comp\(.bz2\)\?\$#d" \
+				    -e "\#^ .* $srclist_.$comp\(.bz2\)\?\$#d" \
+				    -e "\#^ .* $release_.$comp\(.bz2\)\?\$#d" \
+				    -e "s/^\(Components:.*\) $comp\(.*\)\$/\1\2/" \
+					$release.pre > $release.tmp
+				mv -f $release.tmp $release.pre
+			done
+			sed -e "s/^\(Components:.*\)\$/\1 $components/" \
+				$release.pre > $release
+			rm -f $release.pre
+		fi
+		echo "done"
+	else
+		echo -n "Creating global release file... "
+		echo "Origin: Unknown"            >> $release
+		echo "Label: Unknown"             >> $release
+		echo "Suite: Unknown"             >> $release
+		echo "Codename: Unknown"          >> $release
+		echo "Date: `date -R`"            >> $release
+		echo "Architectures: unknown"     >> $release
+		echo "Components: $components"    >> $release
+		echo "Description: Not available" >> $release
+		echo "MD5Sum:"                    >> $release
+		echo "done"
+	fi
+
+	echo -n "Appending MD5Sum..."
+
+	for comp in $components; do
+		echo -n " $comp"
+		if [ -f $pkglist.$comp ]; then
+			phashstuff $pkglist.$comp $pkglist_.$comp >> $release
+			if [ $bz2only -eq 1 ]; then
+				rm -f $pkglist.$comp
+			fi
+		fi
+		if [ -f $srclist.$comp ]; then
+			phashstuff $srclist.$comp $srclist_.$comp >> $release
+			if [ $bz2only -eq 1 ]; then
+				rm -f $srclist.$comp
+			fi
+		fi
+		if [ -f $pkglist.$comp.bz2 ]; then
+			phashstuff $pkglist.$comp.bz2 $pkglist_.$comp.bz2 >> $release
+		fi
+		if [ -f $srclist.$comp.bz2 ]; then
+			phashstuff $srclist.$comp.bz2 $srclist_.$comp.bz2 >> $release
+		fi
+		if [ -f $release.$comp ]; then
+			phashstuff $release.$comp $release_.$comp >> $release
+		fi
+	done
+	echo " done"
+
+	echo >> $release
+
+	if [ $signature -ne 0 ]; then
+		# Use eval because $defaultkey may contain spaces
+		eval gpg --sign -armour --detach-sign --yes --quiet $defaultkey $release
+		cat $release.asc >> $release
+		rm -f $release.asc
+	fi
+
+	# Compare with older release
+	if [ -f $release.old ]; then
+		if cmp -s $release.old $release; then
+			mv -f $release.old $release
+		fi
+		rm -f $release.old
+	fi
 fi
 
-echo "MD5SUM:" >> $hf
 
-pkglist_=${basedir_}/pkglist
-srclist_=${basedir_}/srclist
-release_=${basedir_}/release
-pkglist=${basedir}/pkglist
-srclist=${basedir}/srclist
-release=${basedir}/release
+# old hashfile
+# ------------
 
-for comp in ${components}; do
-    echo -n "${comp}: "
+if [ $oldhashfile -ne 0 -a $listonly -eq 0 ]; then
+	# Save older hashfile
+	hf=$basedir/hashfile
+	if [ -f $hf ]; then
+		mv -f $hf $hf.old
+		if [ $partial -eq 0 ]; then
+			echo -n "Updating legacy hashfile... "
+			echo "MD5SUM:" > $hf
+		else
+			echo -n "Partially updating legacy hashfile file... "
+			sed -n -e "/^\$/q;p" $hf.old > $hf.pre
+			for comp in $components; do
+				sed -e "\#^ .* $pkglist_.$comp\(.bz2\)\?\$#d" \
+				    -e "\#^ .* $srclist_.$comp\(.bz2\)\?\$#d" \
+				    -e "\#^ .* $release_.$comp\(.bz2\)\?\$#d" \
+					$hf.pre > $hf.tmp
+				mv -f $hf.tmp $hf.pre
+			done
+			mv -f $hf.pre $hf
+		fi
+	else
+		echo -n "Creating legacy hashfile... "
+		echo "MD5SUM:" > $hf
+	fi
+	echo "done"
 
-    echo -n "hashfile "
-    if [ -f ${pkglist}.$comp ]; then
-        phashstuff ${pkglist}.$comp ${pkglist_}.$comp >> $hf
-    fi
-    if [ -f ${srclist}.$comp ]; then
-        phashstuff ${srclist}.$comp ${srclist_}.$comp >> $hf
-    fi
+	echo -n "Appending MD5Sum..."
 
-    if [ -f ${pkglist}.$comp.bz2 ]; then
-        phashstuff ${pkglist}.$comp.bz2 ${pkglist_}.$comp.bz2 >> $hf
-    fi
-    if [ -f ${srclist}.$comp.bz2 ]; then
-        phashstuff ${srclist}.$comp.bz2 ${srclist_}.$comp.bz2 >> $hf
-    fi
+	for comp in $components; do
+		echo -n " $comp"
 
-    if [ -f ${release}.$comp ]; then
-	phashstuff ${release}.$comp ${release_}.$comp >> $hf
-    fi
+		if [ -f $pkglist.$comp ]; then
+			phashstuff $pkglist.$comp $pkglist_.$comp >> $hf
+		fi
+		if [ -f $srclist.$comp ]; then
+			phashstuff $srclist.$comp $srclist_.$comp >> $hf
+		fi
+		if [ -f $pkglist.$comp.bz2 ]; then
+			phashstuff $pkglist.$comp.bz2 $pkglist_.$comp.bz2 >> $hf
+		fi
+		if [ -f $srclist.$comp.bz2 ]; then
+			phashstuff $srclist.$comp.bz2 $srclist_.$comp.bz2 >> $hf
+		fi
+		if [ -f $release.$comp ]; then
+			phashstuff $release.$comp $release_.$comp >> $hf
+		fi
+	done
+	echo " done"
 
-    echo "done"
-done
+	echo >> $hf
 
-echo >> $hf
+	# Compare with older hashfile.
+	if [ -f $basedir/hashfile.old ]; then
+		if cmp -s $basedir/hashfile.old $basedir/hashfile; then
+			mv -f $basedir/hashfile.old $basedir/hashfile
+		fi
+	fi
 
-if [ $listonly -eq 0 ]; then
-    # Compare with older hashfile.
-    if [ -f $basedir/hashfile.old ]; then
-        if cmp -s $basedir/hashfile.old $basedir/hashfile; then
-            mv -f $basedir/hashfile.old $basedir/hashfile
-        fi
-    fi
+	if [ $signature -ne 0 ]; then
+
+		# Save older hashfile.gpg
+		if [ -f $basedir/hashfile.gpg ]; then
+			mv -f $basedir/hashfile.gpg $basedir/hashfile.gpg.old
+		fi
+
+		# Use eval because $defaultkey may contain spaces
+		eval gpg --sign --armour --yes --quiet $defaultkey $basedir/hashfile
+		mv -f $basedir/hashfile.asc $basedir/hashfile.gpg
+
+		# Compare with older hashfile.gpg
+		if [ -f $basedir/hashfile.gpg.old ]; then
+			if cmp -s $basedir/hashfile.gpg.old $basedir/hashfile.gpg; then
+				mv -f $basedir/hashfile.gpg.old $basedir/hashfile.gpg
+			fi
+		fi
+	fi
+
+	rm -f $basedir/hashfile.old
+	rm -f $basedir/hashfile.gpg.old
 fi
 
-if [ $signature -ne 0 -a $listonly -eq 0 ]; then
+echo "All your base are belong to us!!!"
 
-    # Save older hashfile.gpg
-    if [ -f $basedir/hashfile.gpg ]; then
-        mv -f $basedir/hashfile.gpg $basedir/hashfile.gpg.old
-    fi
-
-    gpg -armour -qs --yes $basedir/hashfile
-    mv -f $basedir/hashfile.asc $basedir/hashfile.gpg
-    rm -f $basedir/hashfile
-
-    # Compare with older hashfile.gpg
-    if [ -f $basedir/hashfile.gpg.old ]; then
-        if cmp -s $basedir/hashfile.gpg.old $basedir/hashfile.gpg; then
-            mv -f $basedir/hashfile.gpg.old $basedir/hashfile.gpg
-        fi
-    fi
-fi
-
-rm -f $basedir/hashfile.old
-rm -f $basedir/hashfile.gpg.old
-
-echo "All your base are belong to us !!"
-
+# vim:ts=4:sw=4
